server:
  port: 9555
spring:
  application:
    name: test-auth-token
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 60
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30
    service-url:
      defaultZone: http://testService:123aaa@127.0.0.1:9888/eureka/,http://testService:123aaa@127.0.0.1:9999/eureka/
endpoints:
  enabled: true
  health:
    enabled: true
  actuator:
    enabled: true
feign:
  hystrix:
    enable: true
  compression:
    request:
      enable: true
      mime-types: application/json
      min-request-size: 2048
    response:
      enable: true