server:
  port: 9666
spring:
  application:
     name: Web-Client-Service
  data:
    mongodb:
      host: 127.0.0.1
      username: dba
      password: dba
      authentication-database: test #当前用户认证的数据库 在那个数据库创建的用户 在那个数据库认证
      database: test  #不是 Collections文件下面的 而是 指定的库 否则会自定义根据Collection_name创建数据库
      port:  27017
      uri: mongodb://dba:dba@127.0.0.1:27017/test
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10 #获取心跳的时间
    lease-expiration-duration-in-seconds: 30   #间隔时间
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 30    #获取注册中心的服务注册信息 默认为30秒
    service-url:
        defaultZone: http://testService:123aaa@192.168.60.101:9999/eureka/,http://testService:123aaa@192.168.60.101:9888/eureka/
endpoints:
  enabled: true
  health:
    enabled: true
  actuator:
    enabled: true
feign:
  compression:
    request:
      min-request-size: 1024
      mime-types: text/xml,application/json,application/xml
management:
  health:
    mongo:
      enabled: true


